baseURL: https://pbougie.github.io/
cleanDestinationDir: true
disableHugoGeneratorInject: true
disableKinds:
- robotsTXT
- RSS
- taxonomy
- taxonomyTerm
params:
  short_name: P Bougie
  long_name: Patrick Bougie
  description: GitHub User Page for Patrick Bougie.
publishDir: docs # GitHub Pages
